- name: mongodb service
  hosts: mongodb
  become: true

  roles:
    - common

  tasks:
    - name: 启动mongodb container
      docker_container:
        name: mongodb_ansible
        image: mongo
        state: started
        restart: yes
        published_ports: 27017:27017
      vars:
        ansible_python_interpreter: "{{ python3_exec }}"