- name: mongodb service
  hosts: mongodb
  become: true

  tasks:
    - name: 安装Python pip
      yum:
        name: python-pip
        state: present

    - name: 更新Python pip
      pip:
        name: pip
        state: latest

    - name: 安装Python docker模块
      pip:
        name: docker
        state: present

    - name: 安装Python selectors模块
      pip:
        name: selectors
        state: present

    - name: 安装Python typing模块
      pip:
        name: typing
        state: present

    - name: 启动mongodb container
      docker_container:
        name: mongodb_ansible
        image: mongo
        pull: yes
        state: started
        published_ports: 27027:27017