- name: mongodb service
  hosts: mongodb
  become: true

  tasks:
    - name: Install python 3.6 and pip3
      yum:
        name:
          - python36
          - libselinux-python
        state: present

    - name: Install SELinux for Python 3
      pip:
        name:
          - selinux
        state: present
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Install ETLHelper
      pip:
        name:
          - etlhelper
        state: present
        executable: pip3

    - name: 安装Python docker模块
      pip:
        name: docker
        state: present
        executable: pip3

    - name: 安装Python selectors模块
      pip:
        name: selectors
        state: present
        executable: pip3

    - name: 启动mongodb container
      docker_container:
        name: mongodb_ansible
        image: mongo
        state: started
        restart: yes
        published_ports: 27017:27017
      vars:
        ansible_python_interpreter: /usr/bin/python3