- name: mongodb service
  hosts: mongodb
  become: true

  roles:
    - check_py
    - env_py3
    - env_py2
    - common

  tasks:
    - name: 启动mongodb container
      docker_container:
        name: mongodb_ansible
        image: mongo
        state: started
        restart: yes
        published_ports: 27017:27017
        timeout: 10
      vars:
        ansible_python_interpreter: "{{ python3_exec }}"

    - name: Get mongodb container output
      shell: docker logs mongodb_ansible
      register: container_output

    - name: Print mongodb container output
      debug:
        var: container_output.stdout