- name: mongodb service
  hosts: mongodb
  become: true

  tasks:
    - name: 安装Python pip
      yum:
        name: python-pip
        state: present
    - name: 安装Python docker模块
      pip:
        name: docker
        state: present
    - name: 安装Python selector模块
      pip:
        name: selector
        state: present
    - name: 启动mongodb container
      docker_container:
        name: mongodb_ansible
        image: mongo
        pull: yes
        state: started
        published_ports: 27027:27017