- name: zookeeper service
  hosts: zookeeper
  become: true

#  vars:
#    python3_exec: /usr/bin/python3
#    pip3_exec: /usr/bin/pip3

  roles:
    - check_py
    - env_py3
    - env_py2
    - common

  tasks:
    - name: 启动zookeeper container
      docker_container:
        name: zookeeper_ansible
        image: zookeeper
        state: started
        restart: yes
        published_ports: 2181:2181
        timeout: 10
      vars:
        ansible_python_interpreter: "{{ python3_exec }}"

    - name: Get zookeeper container output
      shell: docker logs zookeeper_ansible
      register: container_output

    - name: Print zookeeper container output
      debug:
        var: container_output.stdout