- name: Install python 3.6 and pip3
  yum:
    name:
      - python36
      - libselinux-python
    state: present
  when: py2 is defined

- name: Install SELinux for Python 3
  pip:
    name:
      - selinux
    state: present
    executable: "{{ pip3_exec }}"
  vars:
    ansible_python_interpreter: "{{ python3_exec }}"
  when: py2 is defined