- name: Re-read facts after adding custom fact
  setup:
    filter: ansible_python_version

- name: Get stats of the python3
  vars:
    py2: {{ ansible_python_version }} is match("2.*")

- name: Install python 3.6 and pip3
  yum:
    name:
      - python36
      - libselinux-python
    state: present

- name: Install SELinux for Python 3
  pip:
    name:
      - selinux
    state: present
    executable: {{ pip3_exec }}
  vars:
    ansible_python_interpreter: {{ python3_exec }}