- name: 创建配置目录
  file:
    path: "/data/web/{{ server_port_expose }}/resources/"
    state: directory

- name: 创建application.yml文件
  template:
    src: application.yml.j2
    dest: "/data/web/{{ server_port_expose }}/resources/application.yml"

- name: 启动web container
  docker_container:
    name: "web_{{ server_port_expose }}_ansible"
    image: jxwnhj0717/hello-ansible-web:latest
    pull: yes
    state: started
    restart: yes
    published_ports:
      - "{{ server_port_expose }}:{{ server_port }}"
    volumes:
      - "/data/web/{{ server_port_expose }}/resources/application.yml:/app/resources/application.yml"
#    timeout: 10
  vars:
    ansible_python_interpreter: "{{ python3_exec }}"

- name: Waits for started
  wait_for:
    port: "{{ server_port_expose }}"
    timeout: 10

- name: Get web container output
  shell: docker logs web_{{ server_port_expose }}_ansible
  register: container_output

- name: Print web container output
  debug:
    var: container_output.stdout