- name: Install python 3.6
  dnf:
    name:
      - python3
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install pip 3.6
  dnf:
    name:
      - python3-pip
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install SELinux for Python 3
  dnf:
    name:
      - selinux
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install ETLHelper
  pip:
    name:
      - etlhelper
    state: present
    executable: pip3

- name: 安装Python docker模块
  pip:
    name: docker
    state: present
    executable: pip3

- name: 安装Python selectors模块
  pip:
    name: selectors
    state: present
    executable: pip3

