- name: Install ETLHelper
  pip:
    name:
      - etlhelper
    state: present
    executable: {{ pip3_exec }}

- name: 安装Python docker模块
  pip:
    name: docker
    state: present
    executable: {{ pip3_exec }}

- name: 安装Python selectors模块
  pip:
    name: selectors
    state: present
    executable: {{ pip3_exec }}

