- name: Install python 3.6
  dnf:
    name:
      - python3
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install pip 3.6
  dnf:
    name:
      - python3-pip
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

#- name: Install libselinux-python
#  yum:
#    name:
#      - libselinux-python
#    state: present
#  vars:
#    ansible_python_interpreter: /usr/bin/python2

- name: Install python3-libselinux for Python 3
  dnf:
    name:
      - python3-libselinux
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install ETLHelper
  pip3:
    name:
      - etlhelper
    state: present

- name: 安装Python docker模块
  pip3:
    name: docker
    state: present

- name: 安装Python selectors模块
  pip3:
    name: selectors
    state: present

