- name: Install pip 3.6
  dnf:
    name:
      - python3-pip
    state: present
  vars:
    ansible_python_interpreter: "{{ python3_exec }}"

- name: Install python3-libselinux for Python 3
  dnf:
    name:
      - python3-libselinux
    state: present
  vars:
    ansible_python_interpreter: "{{ python3_exec }}"
